name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Prendre seulement le dernier commit
        uses: actions/checkout@v2
      - name: Composer Install
        run: composer install