name: PHP Composer

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Composer Install
        run: composer install

