name: CI
on:
  push:
    branches:
      - main
  pull_request: ~
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Prendre seulement le dernier commit
        uses: actions/checkout@v2
      - name: Composer Install
        run: composer install
      - name: Check coding standard
        run: vendor/bin/php-cs-fixer fix src --dry-run
      - name: Static code analysis
        run: vendor/bin/phpstan analyze src --level=max
      - name: Unit test
        run: bin/phpunit --testsuite unit
      - name: Integration test
        run: bin/phpunit --testsuite integration
